config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about'

  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top, :about, :public_action]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
      root_path
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    BookComment.find_by(id: params[:id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_user, {only:[:edit, :update, :destroy]}

  def ensure_correct_user
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @user = @book.user
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render :edit
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top

  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_user, {only:[:edit, :update]}

  def ensure_correct_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<%= form_with model: book, url: books_path(book.id), local:true do |f| %>
  <div class="form-group">
    <% if book.errors.any? %>
      <div class="field_with_errors">
        <label for="book_title">Title</label>
      </div>
      <%= f.text_field :title, class: 'form-control book_title', id: 'book_title' %>
    <% else %>
      <label for="book_title">Title</label>
      <%= f.text_field :title, class: 'form-control book_title', id: 'book_title'%>
    <% end %>
  </div>
  <div class="form-group">
    <% if book.errors.any? %>
      <div class="field_with_errors">
        <label for="book_body">Opinion</label>
      </div>
      <%= f.text_area :body, class: 'form-control book_body', id: 'book_body' %>
    <% else %>
      <label for="book_body">Opinion</label>
      <%= f.text_area :body, class: 'form-control book_body', id: 'book_body' %>
    <% end %>
  </div>
  <div class="form-group">
      <%= f.submit 'Create Book', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_error.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h3>
      <% if model.errors.count > 1 %>
        <%= model.errors.count %> errors prohibited this obj from being saved:
      <% else %>
        <%= model.errors.count %> error prohibited this obj from being saved:
      <% end %>
    </h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'books/error', model: @book %>

      <%= form_with model: @book, url: "/books/#{@book.id}", local:true do |f| %>
        <div class="form-group">
          <% if @book.errors.any? %>
            <div class="field_with_errors">
              <label for="book_title">Title</label>
            </div>
            <div class="field_with_errors">
              <%= f.text_field :title, class: 'form-control book_title', id: 'book_title' %>
            </div>
          <% else %>
            <label for="book_title">Title</label>
            <%= f.text_field :title, class: 'form-control book_title', id: 'book_title'%>
          <% end %>
        </div>
        <div class="form-group">
          <% if @book.errors.any? %>
            <div class="field_with_errors">
              <label for="book_body">Opinion</label>
            </div>
            <div class="field_with_errors">
              <%= f.text_area :body, class: 'form-control book_body', id: 'book_body' %>
            </div>
          <% else %>
            <label for="book_body">Opinion</label>
            <%= f.text_area :body, class: 'form-control book_body', id: 'book_body' %>
          <% end %>
        </div>
        <div class="form-group">
            <%= f.submit 'Update Book', class: 'btn btn-success' %>
        </div>
      <% end %>

      <%= link_to "Show", book_path(@book.id), class: "book_#{@book.id}" %>
      |
      <%= link_to "Back", books_path, class: "book_#{@book.id}" %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'books/error', model: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do%>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "noimage.jpg", size: '50x50' %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :delete, class: "book_favorite_#{book.id}" do %>
                      <i class="fas fa-heart" id="heart"><%= book.favorites.count %></i>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :post, class: "book_favorite_#{book.id}" do %>
                      <i class="fas fa-heart"><%= book.favorites.count %></i>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                コメント数：<%= book.book_comments.count %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'books/error', model: @newbook %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @newbook, url: "/books/#{@newbook.id}", local:true do |f| %>
        <div class="form-group">
          <% if @newbook.errors.any? %>
            <div class="field_with_errors">
              <label for="book_title">Title</label>
            </div>
            <div class="field_with_errors">
              <label for="book_title"><%= f.text_field :title, class: 'form-control book_title', id: 'book_title' %></label>
            </div>
          <% else %>
            <label for="book_title">Title</label>
            <%= f.text_field :title, class: 'form-control book_title', id: 'book_title'%>
          <% end %>
        </div>
        <div class="form-group">
          <% if @newbook.errors.any? %>
            <div class="field_with_errors">
              <label for="book_body">Opinion</label>
            </div>
            <div class="field_with_errors">
              <label for="book_body"><%= f.text_area :body, class: 'form-control book_body', id: 'book_body' %></label>
            </div>
          <% else %>
            <label for="book_body">Opinion</label>
            <%= f.text_area :body, class: 'form-control book_body', id: 'book_body' %>
          <% end %>
        </div>
        <div class="form-group">
            <%= f.submit 'Create Book', class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <td>
            <%= link_to user_path(@book.user_id) do%>
                <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "noimage.jpg", size: '50x50' %>
                <br>
                <%= @user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to @book.title, book_path(@book.id), class: "book_#{@book.id}" %>
          </td>
          <td><%= @book.body %></td>
          <td>
            <% if @book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorites_path(@book), method: :delete, class: "book_favorite_#{@book.id}" do %>
                  <i class="fas fa-heart" id="heart"><%= @book.favorites.count %></i>
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to book_favorites_path(@book), method: :post, class: "book_favorite_#{@book.id}" do %>
                  <i class="fas fa-heart"><%= @book.favorites.count %></i>
                <% end %>
              </p>
            <% end %>
          </td>
          <td>
            コメント数：<%= @book.book_comments.count %>
          </td>
          <% if @book.user == current_user %>
            <td>
              <%= link_to 'Edit', edit_book_path(@book.id), class: "btn btn-sm btn-success edit_book_#{@book.id}" %>
            </td>
            <td>
              <%= link_to 'Destroy', book_path(@book), method: :delete,  data: {confirm: "本当に消しますか？"}, class: "btn btn-sm btn-danger destroy_book_#{@book.id}" %>
            </td>
          <% end %>
        </tbody>
      </table>
      <div>
        <% @book.book_comments.each do |book_comment| %>
          <div>
            <%= link_to user_path(book_comment.user_id) do%>
              <%= attachment_image_tag current_user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "noimage.jpg", size: '50x50' %>
            <% end %>
            <%= book_comment.comment %>
            <% if book_comment.user == current_user %>
              <%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger destroy_book_comment_#{@book.id}" %>
            <% end %>
          </div>
          <%= link_to user_path(book_comment.user_id) do%>
            <%= book_comment.user.name %>
          <% end %>
        <% end %>
      </div>
      <div>
        <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <div class="form-group">
            <%= f.text_area :comment, class: 'form-control book_comment', id: 'book_comment' %>
          </div>
          <div class="form-group">
            <%= f.submit "送信" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
    <div class="row">
        <h1 class="px-3 mx-auto">
            Welcome to
            <i class="fas fa-book"></i><strong>Bookers</strong>!
        </h1>
    </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to
        <i class="fas fa-book"></i><strong>Bookers</strong>!!
      </h1>
      <p>
        In
        <i class="fas fa-book"></i><strong>Bookers</strong>,
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in', user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in', href: '/users/sign_in' %>
        </div>
        <div class="row">
          <%= link_to 'Sign up', new_user_session_path, class: 'btn btn-success btn-sm btn-block sign_up', href: '/users/sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to 'Home', user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
                </li>
                <li>
                  <%= link_to 'Users', users_path, class: 'fas fa-users nav-link text-light', href: '/users' %>
                </li>
                <li>
                  <%= link_to 'Books', books_path, class: 'fas fa-book-open nav-link text-light', href: '/books' %>
                </li>
                <li>
                  <%= link_to 'logout', root_path, class: 'fas fa-sign-out-alt nav-link text-light', rel: 'nofollow', method: :delete, href: '/users/sign_out' %>
                </li>
                <% else %>
                <li>
                  <%= link_to 'Home', root_path, class: 'fas fa-home nav-link text-light', href: '/' %>
                </li>
                <li>
                  <%= link_to 'About', home_about_path, class: 'fas fa-link nav-link text-light',  href: '/home/about' %>
                </li>
                <li>
                  <%= link_to 'sign up', new_user_session_path, class: 'fas fa-user-plus nav-link text-light', href: '/users/sign_up' %>
                </li>
                <li>
                  <%= link_to 'login', user_session_path, class: 'fas fa-sign-in-alt nav-link text-light', href: '/users/sign_in' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_user.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg"%>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="row">
  <%= link_to '', edit_user_path(user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model: @user, url: "/users/#{@user.id}", local:true do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h3>
              <% if @user.errors.count > 1 %>
                <%= @user.errors.count %> errors prohibited this book from being saved:
              <% else %>
                <%= @user.errors.count %> error prohibited this book from being saved:
              <% end %>
            </h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li>
                  <%= message %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <% if @user.errors.any? %>
            <div class="field_with_errors">
              <label for="user_name">Name</label>
            </div>
            <div class="field_with_errors">
              <label for="user_name"><%= f.text_field :name, class: 'form-control user_name', id: 'user_name' %></label>
            </div>
          <% else %>
            <label for="user_name">Name</label>
            <%= f.text_field :name, class: 'form-control user_name', id: 'user_name'%>
          <% end %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
            <%= f.text_area :introduction, class: 'form-control user_introduction', id: 'user_introduction' %>
        </div>
        <div class="form-group">
            <%= f.submit 'Update User', class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'books/error', model: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "noimage.jpg", size: '50x50' %>
              </td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", "/users/#{user.id}" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'books/error', model: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user) do%>
                  <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "noimage.jpg", size: '50x50' %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :delete, class: "book_favorite_#{book.id}" do %>
                      <i class="fas fa-heart" id="heart"><%= book.favorites.count %></i>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :post, class: "book_favorite_#{book.id}" do %>
                      <i class="fas fa-heart"><%= book.favorites.count %></i>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                コメント数：<%= book.book_comments.count %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>